default: true
MD003:
  style: "atx"
MD004:
  style: "dash"
MD007:
  indent: 2
MD010: false
MD013:
  line_length: 80
  stern: true
MD022: true
MD024:
  siblings_only: true
MD025: false
MD026: true
MD033: false
MD040: true
MD041: true
MD012: true
MD030:
  ul_single: 1
  ul_multi: 1
MD031: true
MD032: true
MD036: false