site_name: The Lathe Mastery Wiki Book
site_author: Johanness A. Nilsson
site_description: A comprehensive guide to metal lathe operation, from beginer to master
docs_dir: docs
site_dir: site
repo_url: https://github.com/terraform-industry/lathe-mastery-wikibook
repo_name: terraform-industry/lathe-mastery-wikibook

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.instant
    - search.highlight
    - search.share
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - tags

markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols

nav:
  - Home: index.md
  - 01. Foundations:
    - 1.1 The Sacred Contract: 01-foundations/01-sacred-contract.md
    - 1.2 Core Principles: 01-foundations/02-core-principles.md
    - 1.3 Machine Anatomy: 01-foundations/03-machine-anatomy.md
  - 02. Tool Language:
    - 2.1 Tool Materials: 02-tool-language/01-tool-materials.md
    - 2.2 Tool Geometry: 02-tool-language/02-geometry-basics.md
    - 2.3 Grinding Tools: 02-tool-language/03-grinding-tools.md
    - 2.4 Tool Selection: 02-tool-language/04-tool-selection.md
  - 03. Workshop Ecosystem:
    - 3.1 Material Selection: 03-workshop-ecosystem/01-material-selection.md
    - 3.2 Lubricants & Chemicals: 03-workshop-ecosystem/02-lubricants-chemicals.md
  - 04. Fundamental Operations:
    - 4.1 Facing: 04-fundamental-operations/01-facing.md
    - 4.2 Turning Basics: 04-fundamental-operations/02-turning-basics.md
    - 4.3 Turning Shoulders: 04-fundamental-operations/03-turning-shoulders.md
    - 4.4 Supporting Work: 04-fundamental-operations/04-supporting-work.md
  - 05. Precision Measurement:
    - 5.1 Calipers & Micrometers: 05-precision-measurement/01-calipers-micrometers.md
    - 5.2 Dial Indicators: 05-precision-measurement/02-indicators.md
    - 5.3 Specialized Gauges: 05-precision-measurement/03-specialized-gauges.md
  - 06. Advanced Operations:
    - 6.1 Drilling: 06-advanced-operations/01-drilling.md
    - 6.2 Boring: 06-advanced-operations/02-boring.md
    - 6.3 Trepanning: 06-advanced-operations/03-trepanning.md
  - 07. Threading:
    - 7.1 Taps & Dies: 07-threading/01-taps-and-dies.md
    - 7.2 Single-Point Threading: 07-threading/02-single-point-threading.md
    - 7.3 Internal Threading: 07-threading/03-internal-threading.md
  - 08. Critical Operations:
    - 8.1 Parting: 08-critical-operations/01-parting.md
    - 8.2 Surface Finish: 08-critical-operations/02-surface-finish.md
    - 8.3 Speeds & Feeds: 08-critical-operations/03-speeds-and-feeds.md
  - 09. Troubleshooting:
    - 9.1 Defeating Chatter: 09-troubleshooting/01-defeating-chatter.md
    - 9.2 Deburring: 09-troubleshooting/02-deburring.md
  - 10. Advanced Techniques:
    - 10.1 Radius Turning: 10-advanced-techniques/01-radius-turning.md
    - 10.2 Project Planning: 10-advanced-techniques/02-project-planning.md
  - Contributing: CONTRIBUTING.md
  - Authors: AUTHORS.md
  - Changelog: CHANGELOG.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JoNilsson/lathe-mastery-wikibook

copyright: |
  &copy; 2025 <a href="https://github.com/JoNilsson/lathe-mastery-wikibook"  target="_blank" rel="noopener">The Lathe Mastery Wiki Book</a> - 
  <a href="https://creativecommons.org/licenses/by-sa/4.0/"  target="_blank" rel="noopener">CC BY-SA 4.0</a>
